pipeline:
  agent:
    any:
  stages:
    - stage: "Test"
      steps:
        - sh "ls -ltr jen_yml_pipe/"
        - echo "run second script"
    - stage: "Prod"
      steps:
        - echo "run first script"
        - echo "run second script for prod"