pipeline:
  agent:
    any:
  stages:
    - stage: "Test"
      steps:
        - git "https://github.com/TXS881/jen_yml_pipe.git"
        - sh "./sali.sh 20220905"
        - sh "./radar.sh 20220905"
        - echo "QA Job run successfully"
    - stage: "Prod"
      steps:
        - sh "./sali.sh 20220905"
        - sh "./radar.sh 20220905"
        - echo "Prod Job run successfully"